award_me_homepage:
    path:     /
    defaults: { _controller: AwardMeBundle:Site:index }

award_me_welcome:
    path:     /welcome
    defaults: { _controller: AwardMeBundle:Site:welcome }

award_me_add_publication:
    path:     /Publication/add
    defaults: { _controller: AwardMeBundle:Publication:add }

award_me_add_publication_normal:
    path: /Publication/add-normal
    defaults: { _controller: AwardMeBundle:Publication:addPublication }

award_me_add_publication_image:
    path: /Publication/add-image
    defaults: { _controller: AwardMeBundle:Publication:addPublicationImage }

award_me_update_publication:
    path:     /Publication/update/{id}
    defaults: { _controller: AwardMeBundle:Publication:update }

award_me_remove_publication:
    path:     /Publication/remove/{id}
    defaults: { _controller: AwardMeBundle:Publication:remove }

award_me_user_change_avatar:
    path:     /Profile/change-avatar
    defaults: { _controller: UserBundle:Avatar:change }